site_name: TUD-SUMO Wiki
nav:
  - Home: index.md
  - Getting Started: 2_getting_started.md
  - Basic Simulations: 3_basic_sim.md
  - Traffic Demand: 4_demand.md
  - Interacting with the Simulation: 5_interactions.md
  - Tracked Objects: 6_tracked_objs.md
  - Traffic Control: 7_traffic_control.md
  - Events: 8_events.md
  - GUI & Videos: 9_gui.md
  - Plotting Data: 10_plotting.md
  - Examples: 11_examples.md
theme:
  name: material
  font:
    text: Open Sans
  palette:
    primary: custom
    accent: custom
  favicon: img/favicon.ico
  logo: img/logo.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - macros:
      include_dir: include