site_name: TUD-SUMO Wiki
nav:
  - Home: index.md
  - Getting Started: 2_getting_started.md
  - Basic Simulations: 3_basic_sim.md
  - Interacting with the Simulation: 4_interactions.md
  - Tracked Objects: 5_tracked_objs.md
  - Traffic Control: 6_traffic_control.md
  - Events: 7_events.md
  - Plotting Data: 8_plotting.md
  - Example: 9_example.md
theme:
  name: material
  font:
    text: Open Sans
  palette:
    primary: custom
    accent: custom
  favicon: img/favicon.ico
  logo: img/logo.png
extra_css:
- stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences